theme: jekyll-theme-architect
title: 华伦天奴 # 网站标题
subtitle: 一个讲述华伦天奴相关历史的书# 网站副标题
description: 华伦天奴.top # 网站描述(SEO)
author: Denis # 您的名字
language: # 网站使用的语言
timezone: # 网站时区

new_post_name: 2018-12-31-new-years-eve-is-awesome.md
